### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by hellofresh01** [RedSection/jspanda#1]
I am getting a error on running
λ python jspanda.py
Traceback (most recent call last):
  File "C:\Users\Yaseen\Downloads\cmder\jspanda\jspanda.py", line 24, in <module>
    testsite_array = my_file.readlines()
  File "C:\Users\Yaseen\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 484: character maps to <undefined>

**Comment by xsuperbug** [comment]
I tried only for python3.7.x version. When I take a look, it can be solved as follows. 

```
with open('url.txt',encoding="utf8") as my_file:
```

```
with open('url.txt',errors="ignore") as my_file:
```
